### ISSUE TITLE
New Feature: Allow to change font size.

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/DoW-Mod-Manager#30]
Allow the user to change the font size in Dawn of War Soulstorm easily via the Mod Manager, as described in the video below:
https://www.youtube.com/watch?v=hKdl7qtAnYY

**Comment by Fragjacker** [comment]
Are you interested doing this @IgorTheLight ?

**Comment by IgorTheLight** [comment]
I configured those font files myself when I added "A larger fonts" mod ;-)
So this feature request is about being able to change fonts as you want?
I may do that :-)

**Comment by Fragjacker** [comment]
Yeah like add some additional option in the settings to easily set fontsizes from inside Mod Manager and apply it to the game.

**Comment by IgorTheLight** [comment]
I could do that!
Maybe in a few days I would make something like Font Editor for DoW Mod Manager ;-)

**Comment by IgorTheLight** [comment]
I almost finished Font Manager ;-)
User would be able to:
* Change a font of a specific UI item (just copy new font to the special folder).
* Change any font size for most of the screen widths (don't ask me why nor resolutions - that's how DoW game engine works!)

**Comment by IgorTheLight** [comment]
Technically, it's working!
* Adding new fonts using "OPEN FOLDER" button
* Choosing font for many UI elements
* Choosing font sizes for many UI elements and screen resolutions
* Backing up fonts so you could restore them to their default state if you messed something up :-) 

But DoW have a very weird behavior: to change font size for 1920x1080 you should modify settings for 1280x720.
And to change settings for 1280x720 you should modify settings for 800x600.
I tested it manually - same thing. I tried to change it in that way so it would resemble screen height instead of width - same story...
So it's working but I have to understand, how exactly DoW chooses it's font settings.
I could delete all unnecessary strings and just use "sizeDefault" and it would work perfectly. But it's too primitive )and you should change font sizes every time you change your resolution to something new).

**Comment by Fragjacker** [comment]
Excellent! This is pretty much the only missing bit for the Mod Manager. The weird behavior you describe is indeed peculiar but I guess in the end there will be some band-aid code necessary to take this into account. As long as it is consistent in its weird behavior it can be worked out. 😁

**Comment by IgorTheLight** [comment]
True!
I'm considering just to "wire" 1920 to 1280 and so on ;-) It will work for now ;-) There are not so many people with weird resolutions - most people just have 1366x768 (old laptops), 1920x1080 (still very popular), 2560x1440 (most modern gamers have that) and 3840x2160 (4k for the rich boys). So I must test and "fix" those ones first :-)

**Comment by Fragjacker** [comment]
Alright I pushed a new update with a new feature, make sure to update your repository as well 😀 .

**Comment by IgorTheLight** [comment]
Oh, thanks! I will!
Font Manager is hectically ready but I don't like that I have to "fake" some settings because of the DoW weird behavior.
But I will - I can't find another solution for now.

**Comment by Fragjacker** [comment]
This was implemented in commit 19317438ec8d6c1c3999e09f7720154fe5cbb5e3

**Comment by IgorTheLight** [comment]
Good :-)
I will update soon.
